# Based on https://github.com/karlhorky/git-commit-push-workflow-test
name: Modify files, git commit and push

on:
  push:
    branches:
      - '**'      # matches every branch
      - '!main'   # excludes main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2

      - name: "Run replacement scripts to fix Webflow's bad export" 
        run: |
          perl -p -i -e 's/( href="(?!http)[a-zA-Z0-9-]+)\.html"/$1"/g' `grep -ril --include=\*.html '.html' ./`
          perl -p -i -e 's/( href=")((?!http)[a-zA-Z0-9-]+)"/$1\/$2"/g' `grep -ril --include=\*.html '.html' ./`
      - name: Commit files
        run: |
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git pull github ${GITHUB_REF} --ff-only
          git add .
          if [ -z "$(git status --porcelain)" ]; then
            exit 0
          fi
          git commit -m "Fix a[href] in Webflow exported html"
          git push github HEAD:${GITHUB_REF}
